### ISSUE TITLE
nodejs版本的fd demo，报错 error setting argument 0 - "value" argument is out of bounds

### ISSUE THREAD

**Issue by helvenk** [smartkids77/ArcSoft_FreeSDK_Demo#1]
最近要在nodejs项目中增加人脸检索的功能，于是找到了这里来。配置好后node main.js报错。
经排查，是memcpy导致的：
`base.memcpy(ref.address(rect.ref()),
          faceRes.rcFace + base.MRECT.size * i,
          base.MRECT.size); base.memcpy(ref.address(orientBuffer),
          faceRes.lfaceOrient + base.MInt32.size * i,
          base.MInt32.size);
`
尝试将memcpy的参数定义为longlong， 结果上面2条语句执行时就中断了，无输出。
麻烦帮忙解决一下，谢谢
64位的sdk, win10系统，nodejs 8.1

**Comment by smartkids77** [comment]
您好，能否提供下产生BUG时的输入图片
QQ:1628251806

**Comment by smartkids77** [comment]
win64 平台上long 长度和 intptr_t 长度不一致造成的Bug 
已更新修复
